export const countryCodeMapper = {
  AF: { name: 'Afghanistan', isoCode: 'AFG' },
  AX: { name: 'Åland Islands', isoCode: 'ALA' },
  AL: { name: 'Albania', isoCode: 'ALB' },
  DZ: { name: 'Algeria', isoCode: 'DZA' },
  AS: { name: 'American Samoa', isoCode: 'ASM' },
  AD: { name: 'Andorra', isoCode: 'AND' },
  AO: { name: 'Angola', isoCode: 'AGO' },
  AI: { name: 'Anguilla', isoCode: 'AIA' },
  AQ: { name: 'Antarctica', isoCode: 'ATA' },
  AG: { name: 'Antigua and Barbuda', isoCode: 'ATG' },
  AR: { name: 'Argentina', isoCode: 'ARG' },
  AM: { name: 'Armenia', isoCode: 'ARM' },
  AW: { name: 'Aruba', isoCode: 'ABW' },
  AU: { name: 'Australia', isoCode: 'AUS' },
  AT: { name: 'Austria', isoCode: 'AUT' },
  AZ: { name: 'Azerbaijan', isoCode: 'AZE' },
  BS: { name: 'Bahamas', isoCode: 'BHS' },
  BH: { name: 'Bahrain', isoCode: 'BHR' },
  BD: { name: 'Bangladesh', isoCode: 'BGD' },
  BB: { name: 'Barbados', isoCode: 'BRB' },
  BY: { name: 'Belarus', isoCode: 'BLR' },
  BE: { name: 'Belgium', isoCode: 'BEL' },
  BZ: { name: 'Belize', isoCode: 'BLZ' },
  BJ: { name: 'Benin', isoCode: 'BEN' },
  BM: { name: 'Bermuda', isoCode: 'BMU' },
  BT: { name: 'Bhutan', isoCode: 'BTN' },
  BO: { name: 'Bolivia', isoCode: 'BOL' },
  BQ: { name: 'Bonaire Sint Eustatius and Saba', isoCode: 'BES' },
  BA: { name: 'Bosnia and Herzegovina', isoCode: 'BIH' },
  BW: { name: 'Botswana', isoCode: 'BWA' },
  BV: { name: 'Bouvet Island', isoCode: 'BVT' },
  BR: { name: 'Brazil', isoCode: 'BRA' },
  IO: { name: 'British Indian Ocean Territory', isoCode: 'IOT' },
  BN: { name: 'Brunei Darussalam', isoCode: 'BRN' },
  BG: { name: 'Bulgaria', isoCode: 'BGR' },
  BF: { name: 'Burkina Faso', isoCode: 'BFA' },
  BI: { name: 'Burundi', isoCode: 'BDI' },
  CV: { name: 'Cabo Verde', isoCode: 'CPV' },
  KH: { name: 'Cambodia', isoCode: 'KHM' },
  CM: { name: 'Cameroon', isoCode: 'CMR' },
  CA: { name: 'Canada', isoCode: 'CAN' },
  KY: { name: 'Cayman Islands', isoCode: 'CYM' },
  CF: { name: 'Central African Republic', isoCode: 'CAF' },
  TD: { name: 'Chad', isoCode: 'TCD' },
  CL: { name: 'Chile', isoCode: 'CHL' },
  CN: { name: 'China', isoCode: 'CHN' },
  CX: { name: 'Christmas Island', isoCode: 'CXR' },
  CC: { name: 'Cocos', isoCode: 'CCK' },
  CO: { name: 'Colombia', isoCode: 'COL' },
  KM: { name: 'Comoros', isoCode: 'COM' },
  CD: { name: 'Congo', isoCode: 'COD' },
  CG: { name: 'Congo', isoCode: 'COG' },
  CK: { name: 'Cook Islands', isoCode: 'COK' },
  CR: { name: 'Costa Rica', isoCode: 'CRI' },
  CI: { name: "Côte d'Ivoire", isoCode: 'CIV' },
  HR: { name: 'Croatia', isoCode: 'HRV' },
  CU: { name: 'Cuba', isoCode: 'CUB' },
  CW: { name: 'Curaçao', isoCode: 'CUW' },
  CY: { name: 'Cyprus', isoCode: 'CYP' },
  CZ: { name: 'Czechia', isoCode: 'CZE' },
  DK: { name: 'Denmark', isoCode: 'DNK' },
  DJ: { name: 'Djibouti', isoCode: 'DJI' },
  DM: { name: 'Dominica', isoCode: 'DMA' },
  DO: { name: 'Dominican Republic', isoCode: 'DOM' },
  EC: { name: 'Ecuador', isoCode: 'ECU' },
  EG: { name: 'Egypt', isoCode: 'EGY' },
  SV: { name: 'El Salvador', isoCode: 'SLV' },
  GQ: { name: 'Equatorial Guinea', isoCode: 'GNQ' },
  ER: { name: 'Eritrea', isoCode: 'ERI' },
  EE: { name: 'Estonia', isoCode: 'EST' },
  SZ: { name: 'Eswatini', isoCode: 'SWZ' },
  ET: { name: 'Ethiopia', isoCode: 'ETH' },
  FK: { name: 'Falkland Islands  [Malvinas]', isoCode: 'FLK' },
  FO: { name: 'Faroe Islands', isoCode: 'FRO' },
  FJ: { name: 'Fiji', isoCode: 'FJI' },
  FI: { name: 'Finland', isoCode: 'FIN' },
  FR: { name: 'France', isoCode: 'FRA' },
  GF: { name: 'French Guiana', isoCode: 'GUF' },
  PF: { name: 'French Polynesia', isoCode: 'PYF' },
  TF: { name: 'French Southern Territories', isoCode: 'ATF' },
  GA: { name: 'Gabon', isoCode: 'GAB' },
  GM: { name: 'Gambia', isoCode: 'GMB' },
  GE: { name: 'Georgia', isoCode: 'GEO' },
  DE: { name: 'Germany', isoCode: 'DEU' },
  GH: { name: 'Ghana', isoCode: 'GHA' },
  GI: { name: 'Gibraltar', isoCode: 'GIB' },
  GR: { name: 'Greece', isoCode: 'GRC' },
  GL: { name: 'Greenland', isoCode: 'GRL' },
  GD: { name: 'Grenada', isoCode: 'GRD' },
  GP: { name: 'Guadeloupe', isoCode: 'GLP' },
  GU: { name: 'Guam', isoCode: 'GUM' },
  GT: { name: 'Guatemala', isoCode: 'GTM' },
  GG: { name: 'Guernsey', isoCode: 'GGY' },
  GN: { name: 'Guinea', isoCode: 'GIN' },
  GW: { name: 'Guinea-Bissau', isoCode: 'GNB' },
  GY: { name: 'Guyana', isoCode: 'GUY' },
  HT: { name: 'Haiti', isoCode: 'HTI' },
  HM: { name: 'Heard Island and McDonald Islands', isoCode: 'HMD' },
  VA: { name: 'Holy See', isoCode: 'VAT' },
  HN: { name: 'Honduras', isoCode: 'HND' },
  HK: { name: 'Hong Kong', isoCode: 'HKG' },
  HU: { name: 'Hungary', isoCode: 'HUN' },
  IS: { name: 'Iceland', isoCode: 'ISL' },
  IN: { name: 'India', isoCode: 'IND' },
  ID: { name: 'Indonesia', isoCode: 'IDN' },
  IR: { name: 'Iran', isoCode: 'IRN' },
  IQ: { name: 'Iraq', isoCode: 'IRQ' },
  IE: { name: 'Ireland', isoCode: 'IRL' },
  IM: { name: 'Isle of Man', isoCode: 'IMN' },
  IL: { name: 'Israel', isoCode: 'ISR' },
  IT: { name: 'Italy', isoCode: 'ITA' },
  JM: { name: 'Jamaica', isoCode: 'JAM' },
  JP: { name: 'Japan', isoCode: 'JPN' },
  JE: { name: 'Jersey', isoCode: 'JEY' },
  JO: { name: 'Jordan', isoCode: 'JOR' },
  KZ: { name: 'Kazakhstan', isoCode: 'KAZ' },
  KE: { name: 'Kenya', isoCode: 'KEN' },
  KI: { name: 'Kiribati', isoCode: 'KIR' },
  KP: { name: 'Korea', isoCode: 'PRK' },
  KR: { name: 'Korea', isoCode: 'KOR' },
  KW: { name: 'Kuwait', isoCode: 'KWT' },
  KG: { name: 'Kyrgyzstan', isoCode: 'KGZ' },
  LA: { name: "Lao People's Democratic Republic", isoCode: 'LAO' },
  LV: { name: 'Latvia', isoCode: 'LVA' },
  LB: { name: 'Lebanon', isoCode: 'LBN' },
  LS: { name: 'Lesotho', isoCode: 'LSO' },
  LR: { name: 'Liberia', isoCode: 'LBR' },
  LY: { name: 'Libya', isoCode: 'LBY' },
  LI: { name: 'Liechtenstein', isoCode: 'LIE' },
  LT: { name: 'Lithuania', isoCode: 'LTU' },
  LU: { name: 'Luxembourg', isoCode: 'LUX' },
  MO: { name: 'Macao', isoCode: 'MAC' },
  MK: { name: 'Republic of North Macedonia', isoCode: 'MKD' },
  MG: { name: 'Madagascar', isoCode: 'MDG' },
  MW: { name: 'Malawi', isoCode: 'MWI' },
  MY: { name: 'Malaysia', isoCode: 'MYS' },
  MV: { name: 'Maldives', isoCode: 'MDV' },
  ML: { name: 'Mali', isoCode: 'MLI' },
  MT: { name: 'Malta', isoCode: 'MLT' },
  MH: { name: 'Marshall Islands', isoCode: 'MHL' },
  MQ: { name: 'Martinique', isoCode: 'MTQ' },
  MR: { name: 'Mauritania', isoCode: 'MRT' },
  MU: { name: 'Mauritius', isoCode: 'MUS' },
  YT: { name: 'Mayotte', isoCode: 'MYT' },
  MX: { name: 'Mexico', isoCode: 'MEX' },
  FM: { name: 'Micronesia', isoCode: 'FSM' },
  MD: { name: 'Moldova', isoCode: 'MDA' },
  MC: { name: 'Monaco', isoCode: 'MCO' },
  MN: { name: 'Mongolia', isoCode: 'MNG' },
  ME: { name: 'Montenegro', isoCode: 'MNE' },
  MS: { name: 'Montserrat', isoCode: 'MSR' },
  MA: { name: 'Morocco', isoCode: 'MAR' },
  MZ: { name: 'Mozambique', isoCode: 'MOZ' },
  MM: { name: 'Myanmar', isoCode: 'MMR' },
  NA: { name: 'Namibia', isoCode: 'NAM' },
  NR: { name: 'Nauru', isoCode: 'NRU' },
  NP: { name: 'Nepal', isoCode: 'NPL' },
  NL: { name: 'Netherlands', isoCode: 'NLD' },
  NC: { name: 'New Caledonia', isoCode: 'NCL' },
  NZ: { name: 'New Zealand', isoCode: 'NZL' },
  NI: { name: 'Nicaragua', isoCode: 'NIC' },
  NE: { name: 'Niger', isoCode: 'NER' },
  NG: { name: 'Nigeria', isoCode: 'NGA' },
  NU: { name: 'Niue', isoCode: 'NIU' },
  NF: { name: 'Norfolk Island', isoCode: 'NFK' },
  MP: { name: 'Northern Mariana Islands', isoCode: 'MNP' },
  NO: { name: 'Norway', isoCode: 'NOR' },
  OM: { name: 'Oman', isoCode: 'OMN' },
  PK: { name: 'Pakistan', isoCode: 'PAK' },
  PW: { name: 'Palau', isoCode: 'PLW' },
  PS: { name: 'Palestine State of', isoCode: 'PSE' },
  PA: { name: 'Panama', isoCode: 'PAN' },
  PG: { name: 'Papua New Guinea', isoCode: 'PNG' },
  PY: { name: 'Paraguay', isoCode: 'PRY' },
  PE: { name: 'Peru', isoCode: 'PER' },
  PH: { name: 'Philippines', isoCode: 'PHL' },
  PN: { name: 'Pitcairn', isoCode: 'PCN' },
  PL: { name: 'Poland', isoCode: 'POL' },
  PT: { name: 'Portugal', isoCode: 'PRT' },
  PR: { name: 'Puerto Rico', isoCode: 'PRI' },
  QA: { name: 'Qatar', isoCode: 'QAT' },
  RE: { name: 'Réunion', isoCode: 'REU' },
  RO: { name: 'Romania', isoCode: 'ROU' },
  RU: { name: 'Russian Federation', isoCode: 'RUS' },
  RW: { name: 'Rwanda', isoCode: 'RWA' },
  BL: { name: 'Saint Barthélemy', isoCode: 'BLM' },
  SH: {
    name: 'Saint Helena Ascension and Tristan da Cunha',
    isoCode: 'SHN',
  },
  KN: { name: 'Saint Kitts and Nevis', isoCode: 'KNA' },
  LC: { name: 'Saint Lucia', isoCode: 'LCA' },
  MF: { name: 'Saint Martin', isoCode: 'MAF' },
  PM: { name: 'Saint Pierre and Miquelon', isoCode: 'SPM' },
  VC: { name: 'Saint Vincent and the Grenadines', isoCode: 'VCT' },
  WS: { name: 'Samoa', isoCode: 'WSM' },
  SM: { name: 'San Marino', isoCode: 'SMR' },
  ST: { name: 'Sao Tome and Principe', isoCode: 'STP' },
  SA: { name: 'Saudi Arabia', isoCode: 'SAU' },
  SN: { name: 'Senegal', isoCode: 'SEN' },
  RS: { name: 'Serbia', isoCode: 'SRB' },
  SC: { name: 'Seychelles', isoCode: 'SYC' },
  SL: { name: 'Sierra Leone', isoCode: 'SLE' },
  SG: { name: 'Singapore', isoCode: 'SGP' },
  SX: { name: 'Sint Maarten', isoCode: 'SXM' },
  SK: { name: 'Slovakia', isoCode: 'SVK' },
  SI: { name: 'Slovenia', isoCode: 'SVN' },
  SB: { name: 'Solomon Islands', isoCode: 'SLB' },
  SO: { name: 'Somalia', isoCode: 'SOM' },
  ZA: { name: 'South Africa', isoCode: 'ZAF' },
  GS: {
    name: 'South Georgia and the South Sandwich Islands',
    isoCode: 'SGS',
  },
  SS: { name: 'South Sudan', isoCode: 'SSD' },
  ES: { name: 'Spain', isoCode: 'ESP' },
  LK: { name: 'Sri Lanka', isoCode: 'LKA' },
  SD: { name: 'Sudan', isoCode: 'SDN' },
  SR: { name: 'Suriname', isoCode: 'SUR' },
  SJ: { name: 'Svalbard and Jan Mayen', isoCode: 'SJM' },
  SE: { name: 'Sweden', isoCode: 'SWE' },
  CH: { name: 'Switzerland', isoCode: 'CHE' },
  SY: { name: 'Syrian Arab Republic', isoCode: 'SYR' },
  TW: { name: 'Taiwan', isoCode: 'TWN' },
  TJ: { name: 'Tajikistan', isoCode: 'TJK' },
  TZ: { name: 'Tanzania United Republic of', isoCode: 'TZA' },
  TH: { name: 'Thailand', isoCode: 'THA' },
  TL: { name: 'Timor-Leste', isoCode: 'TLS' },
  TG: { name: 'Togo', isoCode: 'TGO' },
  TK: { name: 'Tokelau', isoCode: 'TKL' },
  TO: { name: 'Tonga', isoCode: 'TON' },
  TT: { name: 'Trinidad and Tobago', isoCode: 'TTO' },
  TN: { name: 'Tunisia', isoCode: 'TUN' },
  TR: { name: 'Turkey', isoCode: 'TUR' },
  TM: { name: 'Turkmenistan', isoCode: 'TKM' },
  TC: { name: 'Turks and Caicos Islands', isoCode: 'TCA' },
  TV: { name: 'Tuvalu', isoCode: 'TUV' },
  UG: { name: 'Uganda', isoCode: 'UGA' },
  UA: { name: 'Ukraine', isoCode: 'UKR' },
  AE: { name: 'United Arab Emirates', isoCode: 'ARE' },
  GB: {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    isoCode: 'GBR',
  },
  UM: { name: 'United States Minor Outlying Islands', isoCode: 'UMI' },
  US: { name: 'United States of America', isoCode: 'USA' },
  UY: { name: 'Uruguay', isoCode: 'URY' },
  UZ: { name: 'Uzbekistan', isoCode: 'UZB' },
  VU: { name: 'Vanuatu', isoCode: 'VUT' },
  VE: { name: 'Venezuela', isoCode: 'VEN' },
  VN: { name: 'Viet Nam', isoCode: 'VNM' },
  VG: { name: 'Virgin Islands', isoCode: 'VGB' },
  VI: { name: 'Virgin Islands', isoCode: 'VIR' },
  WF: { name: 'Wallis and Futuna', isoCode: 'WLF' },
  EH: { name: 'Western Sahara', isoCode: 'ESH' },
  YE: { name: 'Yemen', isoCode: 'YEM' },
  ZM: { name: 'Zambia', isoCode: 'ZMB' },
  ZW: { name: 'Zimbabwe', isoCode: 'ZWE' },
};
